//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leetspeak.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leetspeak.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageBanner {
            get {
                object obj = ResourceManager.GetObject("ImageBanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Languages&gt;
        ///	&lt;Language Name=&quot;1337&quot;&gt;
        ///		&lt;Entry English=&quot;a&quot; Leet=&quot;4,4,@&quot; /&gt;
        ///		&lt;Entry English=&quot;i&quot; Leet=&quot;!&quot; /&gt;
        ///		&lt;Entry English=&quot;o&quot; Leet=&quot;0&quot; /&gt;
        ///		&lt;Entry English=&quot;l&quot; Leet=&quot;1&quot; /&gt;
        ///		&lt;Entry English=&quot;e&quot; Leet=&quot;3&quot; /&gt;
        ///		&lt;Entry English=&quot;a&quot; Leet=&quot;4&quot; /&gt;
        ///		&lt;Entry English=&quot;t&quot; Leet=&quot;7&quot; /&gt;
        ///	&lt;/Language&gt;
        ///	&lt;Language Name=&quot;1337 extreme&quot;&gt;
        ///		&lt;Entry English=&quot;a&quot; Leet=&quot;4,@&quot; /&gt;
        ///		&lt;Entry English=&quot;i&quot; Leet=&quot;!,!,1&quot; /&gt;
        ///		&lt;Entry English=&quot;o&quot; Leet=&quot;0&quot; /&gt;
        ///		&lt;Entry English=&quot;l&quot; Leet=&quot;1&quot; /&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
    }
}
